# Generated by Django 3.2.3 on 2021-05-27 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuuid',
            old_name='created_at',
            new_name='created',
        ),
    ]
